In [2]:
import numpy as np

In [4]:
"""
Generate a 3x4 NumPy array with random integers between 1 & 50.
a. Calculate & print the mean, median and standard deviation
b. Print the sum of all elements & the sum of each row
c. Reshape into a 2x6 array and print it.
"""

arr = np.random.randint(1, 51, size=(3,4))
print(arr)

# Calculate & print the mean, median and standard deviation
print(f"Average: {round(arr.mean(), 2)}\nMedian: {np.median(arr)}\nStandard Deviation: {round(arr.std(), 2)}")

# Print the sum of all elements & the sum of each row
print(f"Sum: {arr.sum()}\nSum of each row: {arr.sum(axis=1)}")

# Reshape into a 2x6 array and print it.
print("\nReshaped", arr.reshape((2,6)), sep="\n")

[[48 15 45 24]
 [17 17 49 50]
 [ 3 50 14 33]]
Average: 30.42
Median: 28.5
Standard Deviation: 16.59
Sum: 365
Sum of each row: [132 133 100]

Reshaped
[[48 15 45 24 17 17]
 [49 50  3 50 14 33]]


In [6]:
"""
Create 2 3x3 matrices & print it. Perform the following operations:
a. Matrix Addition
b. Matrix Subtraction
c. Matrix Multiplication
d. Transpose
e. Determinant & Inverse
"""

a = np.random.randint(1, 51, size=(3,3))
b = np.random.randint(1, 51, size=(3,3))
print(f"A = {a}\nB = {b}", sep="\n")

# Matrix Addition
print("\nSum", a+b, sep="\n")

# Matrix Subtraction
print("\nDifference", a-b, sep="\n")

# Matrix Multiplication
print("\nMatrix Dot Product", a@b, sep="\n")
print("\nMatrix Elementwise Product", a*b, sep="\n")

# Transpose
print("\nTranspose of A", np.transpose(a), sep="\n")
print("\nTranspose of B", np.transpose(b), sep="\n")

# Determinant
print("\nDeterminant of A", round(np.linalg.det(a), 2), sep="\n")
print("\nDeterminant of B", round(np.linalg.det(b), 2), sep="\n")

# Inverse
print("\nInverse of A", np.linalg.inv(a), sep="\n")
print("\nInverse of B", np.linalg.inv(b), sep="\n")

A = [[49 31 25]
 [34 36  7]
 [47 50 12]]
B = [[22 43  9]
 [26  3 12]
 [47 13 20]]

Sum
[[71 74 34]
 [60 39 19]
 [94 63 32]]

Difference
[[ 27 -12  16]
 [  8  33  -5]
 [  0  37  -8]]

Matrix Dot Product
[[3059 2525 1313]
 [2013 1661  878]
 [2898 2327 1263]]

Matrix Elementwise Product
[[1078 1333  225]
 [ 884  108   84]
 [2209  650  240]]

Transpose of A
[[49 34 47]
 [31 36 50]
 [25  7 12]]

Transpose of B
[[22 26 47]
 [43  3 13]
 [ 9 12 20]]

Determinant of A
1769.0

Determinant of B
1553.0

Inverse of A
[[ 0.04635387  0.49632561 -0.38609384]
 [-0.044658   -0.33182589  0.2866026 ]
 [ 0.00452233 -0.56133409  0.4013567 ]]

Inverse of B
[[-0.06181584 -0.47842885  0.31487444]
 [ 0.02833226  0.01094656 -0.01931745]
 [ 0.12685126  1.11719253 -0.67739858]]
