In [1]:
import numpy as np

In [51]:
"""
Generate a 3x4 NumPy array with random integers between 1 & 50.
a. Calculate & print the mean, median and standard deviation
b. Print the sum of all elements & the sum of each row
c. Reshape into a 2x6 array and print it.
"""

arr = np.random.randint(1, 50, size=(3,4))
print(arr)

# Calculate & print the mean, median and standard deviation
print(f"Average: {round(arr.mean(), 2)}\nMedian: {np.median(arr)}\nStandard Deviation: {round(arr.std(), 2)}")

# Print the sum of all elements & the sum of each row
print(f"Sum: {arr.sum()}\nSum of each row: {arr.sum(axis=0)}")

# Reshape into a 2x6 array and print it.
print("\nReshaped", arr.reshape((2,6)), sep="\n")

[[29 25  3 46]
 [27 41 13 38]
 [16 14 29 27]]
Average: 25.67
Median: 27.0
Standard Deviation: 12.01
Sum: 308
Sum of each row: [ 72  80  45 111]

Reshaped
[[29 25  3 46 27 41]
 [13 38 16 14 29 27]]


In [60]:
"""
Create 2 3x3 matrices & print it. Perform the following operations:
a. Matrix Addition
b. Matrix Subtraction
c. Matrix Multiplication
d. Transpose
e. Determinant & Inverse
"""

a = np.random.randint(1, 50, size=(3,3))
b = np.random.randint(1, 50, size=(3,3))
print(f"A = {a}\nB = {b}", sep="\n")

# Matrix Addition
print("\nSum", a+b, sep="\n")

# Matrix Subtraction
print("\nDifference", a-b, sep="\n")

# Matrix Multiplication
print("\nMatrix Dot Product", a@b, sep="\n")
print("\nMatrix Elementwise Product", a*b, sep="\n")

# Transpose
print("\nTranspose of A", np.transpose(a), sep="\n")
print("\nTranspose of B", np.transpose(b), sep="\n")

# Determinant
print("\nDeterminant of A", round(np.linalg.det(a), 2), sep="\n")
print("\nDeterminant of B", round(np.linalg.det(b), 2), sep="\n")

# Inverse
print("\nInverse of A", np.linalg.inv(a), sep="\n")
print("\nInverse of B", np.linalg.inv(b), sep="\n")

A = [[22 37 12]
 [18 22  1]
 [47 22 12]]
B = [[26 47 45]
 [49 46  8]
 [30 44  1]]

Sum
[[48 84 57]
 [67 68  9]
 [77 66 13]]

Difference
[[ -4 -10 -33]
 [-31 -24  -7]
 [ 17 -22  11]]

Matrix Dot Product
[[2745 3264 1298]
 [1576 1902  987]
 [2660 3749 2303]]

Matrix Elementwise Product
[[ 572 1739  540]
 [ 882 1012    8]
 [1410  968   12]]

Transpose of A
[[22 18 47]
 [37 22 22]
 [12  1 12]]

Transpose of B
[[26 49 30]
 [47 46 44]
 [45  8  1]]

Determinant of A
-8585.0

Determinant of B
35941.0

Inverse of A
[[-0.0281887   0.0209668   0.02644147]
 [ 0.0196855   0.03494467 -0.02259755]
 [ 0.07431567 -0.14618521  0.02119977]]

Inverse of B
[[-0.00851395  0.05378259 -0.0471328 ]
 [ 0.00531427 -0.03683815  0.05556328]
 [ 0.02159094  0.00740102 -0.03080048]]
